var module = module || {};

module.shared = angular.module('module.shared', [
    'shared.printerFan',
    'shared.addNew',
    'shared.progressBar',
    'shared.printerControls',
    'shared.printerList',
    'shared.printerListItem',
    'shared.notificationList',
    'shared.notificationListItem',
    'shared.loadingScreen',
    'shared.alertBox',
	'shared.float',
	'shared.printerControlsFlowRate',
	'shared.printerControlsSpeed',
	'shared.printerControlsFan',
	'shared.printerControlsSlider',
	'shared.printerSpeed',
	'shared.statusIcon',
	'shared.alertBox',
	'shared.fileDroppable',
	'shared.dashboardWebcam',
	'shared.dashboardTemperatures',
	'shared.onEnter',
	'shared.checkbox',
	'shared.focus',
	'shared.printJobItem',
]);
