language: node_js
sudo: false
node_js:
  - "4"
  - "6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
env:
  - CXX=g++-4.8
install:
  - npm install
deploy:
  provider: npm
  email: chris@printr.nl
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: PRINTR3D/formide-client-2
